fix(errors): Displaying Errors used a deprecated feature in rust, qui…
jasonwhite/ubercopy pull request #61
Opened 2021-06-17 13:37 UTC by mr-bo-jangles

…ck and dirty replace to to_string instead

2021-06-17 18:57 UTC, jasonwhite requested changes

2021-06-17 18:57 UTC, jasonwhite commented on src/error.rs
> +        writeln!(f, "{}:", self.to_string())?;
Thanks for the PR, but did you test this? As far as I can tell this is effectively a recursive call. `self.to_string()` calls `Display::fmt(self, _)`.

2021-06-18 11:12 UTC, mr-bo-jangles commented
No idea, not a rust dev and I just tried to fix the compilation errors for
a friend.

On Thu, 17 Jun 2021, 19:57 Jason White, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/error.rs
> <https://github.com/jasonwhite/ubercopy/pull/61#discussion_r653854240>:
>
> > @@ -124,7 +124,7 @@ Error: Copy verification failed. The source file(s) listed above are either
>
>  impl<'a> fmt::Display for Error<'a> {
>      fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
> -        writeln!(f, "{}:", self.description())?;
> +        writeln!(f, "{}:", self.to_string())?;
>
> Thanks for the PR, but did you test this? As far as I can tell this is
> effectively a recursive call. self.to_string() calls Display::fmt(self, _)
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jasonwhite/ubercopy/pull/61#pullrequestreview-686694358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACHF4TJYOGZSUIOK5DOLZ3TTJARDANCNFSM463WHR4A>
> .
>

2021-06-18 17:25 UTC, jasonwhite commented
Closing this as it doesn't fix anything.

2021-06-18 17:25 UTC, closed without merging